[package]
name = "raytracer"
version = "0.1.0"
authors = ["Avarel <avarelpm@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.3"
ultraviolet = "0.4"
rand = "0.7"
image = "0.22.3"
indicatif = "0.13"